import type { BarChartSchema } from '@visactor/vinfo-graphics';

export const barExamples: { name: string; schema: BarChartSchema }[] = [
  {
    name: '基础条形图',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      theme: 'tiktok',
    },
  },
  {
    name: '降序排列',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（降序）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
    },
  },
  {
    name: '带外标签',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（带标签）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      label: {
        visible: true,
        position: 'outside',
        format: '{value}万',
      },
    },
  },
  {
    name: '带内标签',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（内标签）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      label: {
        visible: true,
        position: 'inside-right',
        format: '{value}',
      },
    },
  },
  {
    name: '圆角条形',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（圆角）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      bar: {
        cornerRadius: 8,
      },
    },
  },
  {
    name: '标题右侧',
    schema: {
      chartType: 'bar',
      title: {
        text: '各平台用户数',
        position: 'right',
      },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
    },
  },
  {
    name: '自定义颜色',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      colors: ['#5B8FF9', '#5AD8A6', '#F6BD16', '#E86452', '#6DC8EC'],
    },
  },
  {
    name: '带背景',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      background: {
        color: '#f0f5ff',
      },
    },
  },
  {
    name: '渐变填充',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（渐变）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      bar: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#FF6B6B', '#4ECDC4'],
        },
      },
    },
  },
  {
    name: '渐变+圆角+顶部标签',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      bar: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#5B8FF9', '#5AD8A6'],
        },
        cornerRadius: 8,
      },
      label: {
        visible: true,
        position: 'top-right',
        format: '{value}',
      },
    },
  },
  {
    name: '排名标签',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（排名）' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      rank: {
        visible: true,
        position: 'start',
        style: {
          fontSize: 12,
          fill: '#fff',
          fontWeight: 'bold',
          backgroundColor: '#5B8FF9',
        },
      },
    },
  },
  {
    name: '渐变+排名',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数' },
      data: [
        { platform: '微信', users: 1200 },
        { platform: '抖音', users: 980 },
        { platform: '微博', users: 650 },
        { platform: '快手', users: 520 },
        { platform: 'B站', users: 380 },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      bar: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#FF6B6B', '#FFEAA7'],
        },
      },
      rank: {
        visible: true,
        position: 'start',
        style: {
          fontSize: 14,
          fill: '#fff',
          fontWeight: 'bold',
          backgroundColor: '#FF6B6B',
          cornerRadius: 6,
        },
      },
    },
  },
  {
    name: '背景图标',
    schema: {
      chartType: 'bar',
      title: { text: '各平台用户数（背景图标）' },
      data: [
        { platform: '微信', users: 1200, bgIcon: 'wechat' },
        { platform: '抖音', users: 980, bgIcon: 'douyin' },
        { platform: '微博', users: 650, bgIcon: 'weibo' },
        { platform: '快手', users: 520, bgIcon: 'kuaishou' },
        { platform: 'B站', users: 380, bgIcon: 'bilibili' },
      ],
      categoryField: 'platform',
      valueField: 'users',
      sort: 'desc',
      icon: {
        visible: true,
        field: 'bgIcon',
        map: {
          wechat: 'https://img.icons8.com/wc',
          douyin: 'https://img.icons8.com/tiktok',
          weibo: 'https://img.icons8.com/weibo',
          kuaishou: 'https://img.icons8.com/search',
          bilibili: 'https://img.icons8.com/bilibili',
        },
      },
    },
  },
  {
    name: '工作年龄人口Top20（图像复刻）',
    schema: {
      chartType: 'bar',
      title: { text: 'Cities with the Largest Working-Age Populations (2024)' },
      data: [
        { city: 'Shanghai', value: 18.4, flag: 'cn' },
        { city: 'Beijing', value: 16.5, flag: 'cn' },
        { city: 'Delhi-Gurugram', value: 15.7, flag: 'in' },
        { city: 'Guangzhou', value: 15.6, flag: 'cn' },
        { city: 'Shenzhen', value: 15.5, flag: 'cn' },
        { city: 'New York Metro', value: 13.3, flag: 'us' },
        { city: 'São Paulo', value: 12.0, flag: 'br' },
        { city: 'Mexico City*', value: 11.8, flag: 'mx' },
        { city: 'Bengaluru', value: 10.3, flag: 'in' },
        { city: 'Manila', value: 10.0, flag: 'ph' },
        { city: 'Buenos Aires*', value: 9.8, flag: 'ar' },
        { city: 'Mumbai', value: 9.6, flag: 'in' },
        { city: 'Tokyo', value: 9.1, flag: 'jp' },
        { city: 'LA-Orange County', value: 8.6, flag: 'us' },
        { city: 'Paris', value: 8.1, flag: 'fr' },
        { city: 'Seoul', value: 6.8, flag: 'kr' },
        { city: 'London', value: 6.5, flag: 'gb' },
        { city: 'Bogotá*', value: 6.3, flag: 'co' },
        { city: 'Chicago', value: 6.2, flag: 'us' },
        { city: 'Dallas-Ft. Worth', value: 5.6, flag: 'us' },
      ],
      categoryField: 'city',
      valueField: 'value',
      sort: 'desc',
      bar: {
        cornerRadius: 999,
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '{value}M',
      },
      icon: {
        visible: true,
        field: 'flag',
        map: {
          cn: 'https://flagcdn.com/w80/cn.png',
          in: 'https://flagcdn.com/w80/in.png',
          us: 'https://flagcdn.com/w80/us.png',
          br: 'https://flagcdn.com/w80/br.png',
          mx: 'https://flagcdn.com/w80/mx.png',
          ph: 'https://flagcdn.com/w80/ph.png',
          ar: 'https://flagcdn.com/w80/ar.png',
          jp: 'https://flagcdn.com/w80/jp.png',
          fr: 'https://flagcdn.com/w80/fr.png',
          kr: 'https://flagcdn.com/w80/kr.png',
          gb: 'https://flagcdn.com/w80/gb.png',
          co: 'https://flagcdn.com/w80/co.png',
        },
        position: 'start',
      },
      colors: [
        '#DD2E44',
        '#D7263D',
        '#0FAF6E',
        '#D92A3A',
        '#D82C3B',
        '#2E6FD6',
        '#0D95A8',
        '#57B86A',
        '#12AE62',
        '#F2BD17',
        '#1B95F2',
        '#17A66A',
        '#E83F8A',
        '#2D62C9',
        '#FF6A00',
        '#8B4BD8',
        '#C3008B',
        '#0D67B4',
        '#2C67C9',
        '#2A66C8',
      ],
      background: {
        color: '#F4EEE2',
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: 'GEN Z 数字娱乐（图像复刻）',
    schema: {
      chartType: 'bar',
      title: {
        text: "GEN Z'S Digital Entertainment",
        subtext: '% of U.S. Gen Z population engaged in digital activity at least once a month...',
      },
      data: [
        { activity: 'Digital video viewers', percent: 96, icon: 'video' },
        { activity: 'Social network users', percent: 88, icon: 'social' },
        { activity: 'Digital buyers', percent: 82, icon: 'bag' },
        { activity: 'Podcast listeners', percent: 57, icon: 'podcast' },
        { activity: 'VR/AR users', percent: 37, icon: 'vr' },
      ],
      categoryField: 'activity',
      valueField: 'percent',
      sort: 'desc',
      background: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#DFFF4F', '#C9F13A'],
        },
      },
      bar: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#7F65E9', '#5822C9'],
        },
        cornerRadius: 28,
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '{value}%',
      },
      icon: {
        visible: true,
        field: 'icon',
        map: {
          video: 'https://img.icons8.com/color/96/video.png',
          social: 'https://img.icons8.com/color/96/group.png',
          bag: 'https://img.icons8.com/color/96/shopping-bag.png',
          podcast: 'https://img.icons8.com/color/96/headphones.png',
          vr: 'https://img.icons8.com/color/96/vr-glasses.png',
        },
        position: 'start',
        style: {
          lineWidth: 2,
          stroke: '#9D8AF0',
        },
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: '标普500高回报（图像复刻）',
    schema: {
      chartType: 'bar',
      title: {
        text: 'S&P 500 Companies with Highest Yearly Returns',
        subtext: 'Annualized returns (2005-2024)',
        position: 'right',
      },
      data: [
        { company: 'NVIDIA', returns: 39.2, logo: 'nvidia' },
        { company: 'Netflix', returns: 36.5, logo: 'netflix' },
        { company: 'Apple', returns: 32.0, logo: 'apple' },
        { company: 'Booking Holdings', returns: 30.7, logo: 'booking' },
        { company: 'Texas Pacific Land Corporation', returns: 28.4, logo: 'tpl' },
        { company: 'Monster Energy', returns: 28.0, logo: 'monster' },
        { company: 'Intuitive Surgical', returns: 26.9, logo: 'intuitive' },
        { company: 'Amazon', returns: 25.8, logo: 'amazon' },
        { company: 'Salesforce', returns: 24.4, logo: 'salesforce' },
        { company: 'Deckers Brands', returns: 24.3, logo: 'deckers' },
        { company: 'Regeneron', returns: 24.3, logo: 'regeneron' },
        { company: 'MPS', returns: 24.0, logo: 'mps' },
        { company: 'Tyler Technologies', returns: 23.6, logo: 'tyler' },
        { company: 'FICO', returns: 22.3, logo: 'fico' },
        { company: 'Old Dominion Freight Line', returns: 22.0, logo: 'odfl' },
        { company: "O'Reilly Auto Parts", returns: 21.9, logo: 'oreilly' },
        { company: "Domino's", returns: 21.7, logo: 'dominos' },
        { company: 'Quanta Services', returns: 20.3, logo: 'quanta' },
        { company: 'Lennox', returns: 20.2, logo: 'lennox' },
        { company: 'Alphabet', returns: 20.2, logo: 'alphabet' },
      ],
      categoryField: 'company',
      valueField: 'returns',
      sort: 'desc',
      background: {
        color: '#E7ECDB',
      },
      bar: {
        cornerRadius: 2,
        linearGradient: {
          direction: 'left-right',
          colors: ['#F4F8EF', '#6BC60B', '#176E2F'],
        },
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '{value}%',
      },
      icon: {
        visible: true,
        field: 'logo',
        label: {
          visible: true,
        },
        map: {
          nvidia: 'https://logo.clearbit.com/nvidia.com',
          netflix: 'https://logo.clearbit.com/netflix.com',
          apple: 'https://logo.clearbit.com/apple.com',
          booking: 'https://logo.clearbit.com/bookingholdings.com',
          tpl: 'https://logo.clearbit.com/tplp.com',
          monster: 'https://logo.clearbit.com/monsterenergy.com',
          intuitive: 'https://logo.clearbit.com/intuitive.com',
          amazon: 'https://logo.clearbit.com/amazon.com',
          salesforce: 'https://logo.clearbit.com/salesforce.com',
          deckers: 'https://logo.clearbit.com/deckers.com',
          regeneron: 'https://logo.clearbit.com/regeneron.com',
          mps: 'https://logo.clearbit.com/monolithicpower.com',
          tyler: 'https://logo.clearbit.com/tylertech.com',
          fico: 'https://logo.clearbit.com/fico.com',
          odfl: 'https://logo.clearbit.com/odfl.com',
          oreilly: 'https://logo.clearbit.com/oreillyauto.com',
          dominos: 'https://logo.clearbit.com/dominos.com',
          quanta: 'https://logo.clearbit.com/quantaservices.com',
          lennox: 'https://logo.clearbit.com/lennox.com',
          alphabet: 'https://logo.clearbit.com/abc.xyz',
        },
        position: 'start',
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: '博彩支出Top10州（图像复刻）',
    schema: {
      chartType: 'bar',
      title: {
        text: 'Top 10 States by Gambling Spending',
        subtext: '2023 Revenue USD',
        position: 'right',
      },
      data: [
        { state: 'Nevada', revenue: 15.5 },
        { state: 'Pennsylvania', revenue: 5.9 },
        { state: 'New Jersey', revenue: 5.8 },
        { state: 'New York', revenue: 4.7 },
        { state: 'Michigan', revenue: 3.6 },
        { state: 'Ohio', revenue: 3.3 },
        { state: 'Indiana', revenue: 2.8 },
        { state: 'Louisiana', revenue: 2.7 },
        { state: 'Illinois', revenue: 2.5 },
        { state: 'Maryland', revenue: 2.5 },
        { state: 'Rest of US', revenue: 17.3 },
      ],
      categoryField: 'state',
      valueField: 'revenue',
      sort: 'none',
      background: {
        linearGradient: {
          direction: 'left-right',
          colors: ['#101518', '#1A2025'],
        },
      },
      colors: [
        '#EED89A',
        '#E6C66C',
        '#F0C84F',
        '#F4BA06',
        '#F0AE03',
        '#E8A904',
        '#D89E05',
        '#C09105',
        '#B88607',
        '#A57B11',
        '#A07705',
      ],
      bar: {
        cornerRadius: 0,
      },
      rank: {
        visible: true,
        position: 'yAxis',
        // style: {
        //   fontSize: 14,
        //   fill: '#F4C52A',
        //   fontWeight: 'bold',
        //   backgroundColor: 'white',
        // },
      },
      label: {
        visible: true,
        position: 'outside',
        format: '${value}B',
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: '美国最佳大学学费（复刻简化版）',
    schema: {
      chartType: 'bar',
      title: {
        text: 'Best Universities in America',
        subtext: '2023-2024 Tuition and Fees (USD, Thousands)',
        position: 'left',
      },
      data: [
        { rank: 1, university: 'Princeton', tuition: 59.7, type: 'private' },
        { rank: 2, university: 'MIT', tuition: 60.2, type: 'private' },
        { rank: 3, university: 'Harvard', tuition: 59.1, type: 'private' },
        { rank: 4, university: 'Stanford', tuition: 62.5, type: 'private' },
        { rank: 5, university: 'Yale', tuition: 64.7, type: 'private' },
        { rank: 6, university: 'Penn', tuition: 66.1, type: 'private' },
        { rank: 7, university: 'Caltech', tuition: 63.0, type: 'private' },
        { rank: 8, university: 'Duke', tuition: 66.2, type: 'private' },
        { rank: 9, university: 'Brown', tuition: 68.2, type: 'private' },
        { rank: 10, university: 'Northwestern', tuition: 60.0, type: 'private' },
        { rank: 15, university: 'Berkeley (CA)', tuition: 46.3, type: 'public' },
        { rank: 16, university: 'UCLA', tuition: 46.3, type: 'public' },
        { rank: 20, university: 'University of Michigan', tuition: 57.3, type: 'public' },
      ],
      categoryField: 'university',
      valueField: 'tuition',
      sort: 'desc',
      background: {
        color: '#FAFAFA',
      },
      bar: {
        cornerRadius: 3,
        linearGradient: {
          direction: 'left-right',
          colors: ['#003D7A', '#1565C0'],
        },
      },
      rank: {
        visible: true,
        position: 'start',
        // style: {
        //   fontSize: 12,
        //   fill: '#fff',
        //   fontWeight: 'bold',
        //   backgroundColor: '#003D7A',
        //   cornerRadius: 12,
        // },
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '${value}K',
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: '美国最受欢迎新闻网站（复刻简化版）',
    schema: {
      chartType: 'bar',
      title: {
        text: "What is AMERICA'S FAVOURITE NEWS WEBSITE?",
        subtext:
          'As of Q3 2025. Percentage represents people who have a favorable opinion of a news website.',
        position: 'left',
      },
      data: [
        { rank: 1, website: 'Yahoo', favorable: 58, type: 'legacy-digital' },
        { rank: 2, website: 'CNN.com', favorable: 49, type: 'cable-news' },
        { rank: 3, website: 'BBC News', favorable: 47, type: 'mainstream' },
        { rank: 4, website: 'NBC.com', favorable: 47, type: 'mainstream' },
        { rank: 5, website: 'NPR News', favorable: 43, type: 'mainstream' },
        { rank: 6, website: 'NYTimes.com', favorable: 42, type: 'legacy-digital' },
        { rank: 7, website: 'CBS.com', favorable: 41, type: 'mainstream' },
        { rank: 8, website: 'Reuters', favorable: 40, type: 'legacy-digital' },
        { rank: 9, website: 'MSN.com', favorable: 39, type: 'cable-news' },
        { rank: 10, website: 'BCNews.com', favorable: 39, type: 'mainstream' },
        { rank: 11, website: 'CNBC', favorable: 36, type: 'cable-news' },
        { rank: 12, website: 'ESPN.com', favorable: 36, type: 'cable-sports' },
        { rank: 13, website: 'Washington Post', favorable: 35, type: 'legacy-digital' },
        { rank: 14, website: 'NFL.COM', favorable: 34, type: 'cable-sports' },
        { rank: 15, website: 'Forbes.com', favorable: 33, type: 'digital-only' },
        { rank: 16, website: 'US Weekly', favorable: 30, type: 'legacy-digital' },
        { rank: 17, website: 'Bloomberg', favorable: 29, type: 'cable-news' },
        { rank: 18, website: 'FT Online', favorable: 29, type: 'legacy-digital' },
        { rank: 19, website: 'TMZ', favorable: 29, type: 'digital-only' },
        { rank: 20, website: 'CBS Sports Mobile', favorable: 28, type: 'cable-sports' },
        { rank: 21, website: 'CNET.com', favorable: 28, type: 'digital-only' },
        { rank: 22, website: 'onNews.com', favorable: 28, type: 'digital-only' },
        { rank: 23, website: 'POLITICO', favorable: 28, type: 'digital-only' },
        { rank: 24, website: 'Buzzfeed', favorable: 27, type: 'digital-only' },
        { rank: 25, website: 'Fox Business', favorable: 27, type: 'cable-news' },
        { rank: 26, website: 'HuffPost', favorable: 27, type: 'digital-only' },
        { rank: 27, website: 'The Hill', favorable: 27, type: 'digital-only' },
        { rank: 28, website: 'Vox', favorable: 25, type: 'digital-only' },
        { rank: 29, website: 'Military.com', favorable: 24, type: 'digital-only' },
        { rank: 30, website: 'PCMag.com', favorable: 24, type: 'digital-only' },
      ],
      categoryField: 'website',
      valueField: 'favorable',
      sort: 'none',
      background: {
        color: '#FEF5E7',
      },
      bar: {
        cornerRadius: 4,
        linearGradient: {
          direction: 'left-right',
          colors: ['#2E86DE', '#54A0FF'],
        },
      },
      footnote: {
        image:
          'https://lf-dp.bytetos.com/obj/dp-open-internet-cn/visactor-site/bytedance/client/img/vchart/galleryStreamGraph.png',
        text: 'Source: Morning Consult, Q3 2025. Base: U.S. adults aged 18+ who have a favorable or unfavorable opinion of at least one news website.',
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '${value}%',
      },
      rank: {
        visible: false,
      },
      xAxis: {
        visible: false,
      },
      yAxis: {
        visible: true,
      },
      legend: { visible: false },
    },
  },
  {
    name: '复刻图片',
    schema: {
      chartType: 'bar',
      title: {
        text: "Gen Z's Digital Entertainment",
        subtext: '% of U.S. Gen Z population engaged in digital activity at least once a month...',
        position: 'center',
      },
      footnote: {
        text: 'Source: EMARKETER. Data as of May 2024. Digital buyers are users who have made one purchase through any digital channel.',
        layout: 'left',
        fontSize: 12,
        fill: '#4B5563',
      },
      width: 800,
      height: 600,
      background: {
        color: '#D6FF57',
      },
      theme: 'fresh',
      colors: ['#8B5CF6'],
      data: [
        {
          category: 'Digital video viewers',
          value: 96,
          iconKey: 'Digital video viewers',
        },
        {
          category: 'Social network users',
          value: 88,
          iconKey: 'Social network users',
        },
        {
          category: 'Digital buyers',
          value: 82,
          iconKey: 'Digital buyers',
        },
        {
          category: 'Podcast listeners',
          value: 57,
          iconKey: 'Podcast listeners',
        },
        {
          category: 'VR/AR users',
          value: 37,
          iconKey: 'VR/AR users',
        },
      ],
      categoryField: 'category',
      valueField: 'value',
      sort: 'desc',
      bar: {
        cornerRadius: 8,
        gap: 10,
        linearGradient: {
          direction: 'left-right',
          colors: ['#8B5CF6', '#C4B5FD'],
        },
      },
      label: {
        visible: true,
        position: 'inside-right',
        format: '{value}%',
        minVisible: 0,
      },
      icon: {
        field: 'iconKey',
        map: {
          'Digital video viewers': 'https://api.iconify.design/mdi/clock-digital.svg',
          'Social network users': 'https://api.iconify.design/mdi/digital-ocean.svg',
          'Digital buyers': 'https://api.iconify.design/mdi/perm-media.svg',
          'Podcast listeners': 'https://api.iconify.design/mdi/folder-media.svg',
          'VR/AR users': 'https://api.iconify.design/mdi/folder-media-outline.svg',
        },
        visible: true,
        position: 'start',
        size: 24,
        style: {
          lineWidth: 2,
          stroke: '#FFFFFF',
        },
      },
    },
  },
];
