import type { PieChartSchema } from '@visactor/vinfo-graphics';

export const pieExamples: { name: string; schema: PieChartSchema }[] = [
  {
    name: '环形图带中心图片',
    schema: {
      chartType: 'pie',
      title: { text: '用户分布' },
      data: [
        { name: '00后', value: 15 },
        { name: '90后', value: 35 },
        { name: '80后', value: 30 },
        { name: '70后', value: 15 },
        { name: '其他', value: 5 },
      ],
      categoryField: 'name',
      valueField: 'value',
      innerRadius: 0.5,
      outerRadius: 0.8,
      centerImage: {
        visible: true,
        url: 'https://lf-dp.bytetos.com/obj/dp-open-internet-cn/visactor-site/bytedance/client/img/vchart/galleryStreamGraph.png',
        width: 50,
        height: 50,
      },
      theme: 'uranium',
    },
  },
  {
    name: '环形图带扇区图标和中心图片',
    schema: {
      chartType: 'pie',
      title: { text: '社交媒体市场份额' },
      data: [
        { platform: '微信', value: 35, icon: 'wechat' },
        { platform: '抖音', value: 28, icon: 'douyin' },
        { platform: '微博', value: 18, icon: 'weibo' },
        { platform: '小红书', value: 12, icon: 'xiaohongshu' },
        { platform: '其他', value: 7, icon: 'other' },
      ],
      categoryField: 'platform',
      valueField: 'value',
      innerRadius: 0.55,
      outerRadius: 0.85,
      colors: ['#07C160', '#000000', '#E6162D', '#FF2442', '#9AA3AD'],
      icon: {
        visible: true,
        field: 'icon',
        size: 20,
        map: {
          wechat: 'https://img.icons8.com/color/96/video.png',
          douyin: 'https://img.icons8.com/color/96/video.png',
          weibo: 'https://img.icons8.com/color/96/video.png',
          xiaohongshu: 'https://img.icons8.com/color/96/video.png',
          other: 'https://img.icons8.com/color/96/video.png',
        },
      },
      centerImage: {
        visible: true,
        url: 'https://lf-dp.bytetos.com/obj/dp-open-internet-cn/visactor-site/bytedance/client/img/vchart/galleryStreamGraph.png',
        width: 60,
        height: 60,
      },
      label: {
        visible: true,
        position: 'outside',
        format: '{name}: {value}%',
      },
      legend: { visible: false },
    },
  },
  {
    name: '基础饼图',
    schema: {
      chartType: 'pie',
      title: { text: '市场份额' },
      data: [
        { name: '产品A', value: 30 },
        { name: '产品B', value: 25 },
        { name: '产品C', value: 20 },
        { name: '产品D', value: 15 },
        { name: '其他', value: 10 },
      ],
      categoryField: 'name',
      valueField: 'value',
    },
  },
  {
    name: '环形图',
    schema: {
      chartType: 'pie',
      title: { text: '用户分布' },
      data: [
        { name: '00后', value: 15 },
        { name: '90后', value: 35 },
        { name: '80后', value: 30 },
        { name: '70后', value: 15 },
        { name: '其他', value: 5 },
      ],
      categoryField: 'name',
      valueField: 'value',
      innerRadius: 0.5,
      outerRadius: 0.8,
    },
  },
  {
    name: '带外标签',
    schema: {
      chartType: 'pie',
      title: { text: '市场份额（带标签）' },
      data: [
        { name: '产品A', value: 30 },
        { name: '产品B', value: 25 },
        { name: '产品C', value: 20 },
        { name: '产品D', value: 15 },
        { name: '其他', value: 10 },
      ],
      categoryField: 'name',
      valueField: 'value',
      label: {
        visible: true,
        position: 'outside',
      },
    },
  },
  {
    name: '带内标签',
    schema: {
      chartType: 'pie',
      title: { text: '市场份额（内标签）' },
      data: [
        { name: '产品A', value: 30 },
        { name: '产品B', value: 25 },
        { name: '产品C', value: 20 },
        { name: '产品D', value: 15 },
        { name: '其他', value: 10 },
      ],
      categoryField: 'name',
      valueField: 'value',
      innerRadius: 0.4,
      label: {
        visible: true,
        position: 'inside',
      },
    },
  },
  {
    name: '自定义颜色',
    schema: {
      chartType: 'pie',
      title: { text: '自定义颜色' },
      data: [
        { name: '产品A', value: 30 },
        { name: '产品B', value: 25 },
        { name: '产品C', value: 20 },
        { name: '产品D', value: 15 },
        { name: '其他', value: 10 },
      ],
      categoryField: 'name',
      valueField: 'value',
      colors: ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7'],
    },
  },
  {
    name: '标题在右侧',
    schema: {
      chartType: 'pie',
      title: {
        text: '市场份额',
        position: 'right',
      },
      data: [
        { name: '产品A', value: 30 },
        { name: '产品B', value: 25 },
        { name: '产品C', value: 20 },
        { name: '产品D', value: 15 },
        { name: '其他', value: 10 },
      ],
      categoryField: 'name',
      valueField: 'value',
    },
  },
  {
    name: '印度国内航司份额（复刻简化版）',
    schema: {
      chartType: 'pie',
      title: {
        text: 'INDIAN DOMESTIC AIRLINE MARKET LEADERS',
        subtext: 'Share of domestic market (%)',
        position: 'center',
      },
      data: [
        { airline: 'IndiGo', share: 65.2 },
        { airline: 'Air India', share: 27.2 },
        { airline: 'Akasa Air', share: 5 },
        { airline: 'SpiceJet', share: 2.6 },
      ],
      categoryField: 'airline',
      valueField: 'share',
      innerRadius: 0.72,
      outerRadius: 0.9,
      colors: ['#0F2AA6', '#D6003A', '#6C2BD9', '#F39C12'],
      background: {
        color: '#EEF2F7',
      },
      label: {
        visible: true,
        position: 'inside',
        format: '{value}%',
      },
      legend: { visible: false },
    },
  },
  {
    name: 'Oracle Q4 2025 组合（复刻简化版）',
    schema: {
      chartType: 'pie',
      title: {
        text: "THE ORACLE'S ALLOCATION: Q4 2025 PORTFOLIO SNAPSHOT",
        subtext: 'Top positions percentage distribution',
        position: 'center',
      },
      data: [
        { holding: 'Apple', weight: 22.6 },
        { holding: 'American Express', weight: 20.46 },
        { holding: 'Bank of America', weight: 10.38 },
        { holding: 'Coca-Cola', weight: 10.2 },
        { holding: 'Chevron', weight: 7.24 },
        { holding: "Moody's", weight: 4.6 },
        { holding: 'Occidental Petroleum', weight: 3.97 },
        { holding: 'Chubb Limited', weight: 3.9 },
        { holding: 'The Kraft Heinz Company', weight: 2.88 },
        { holding: 'Alphabet', weight: 2.04 },
        { holding: 'DaVita', weight: 1.32 },
        { holding: 'Kroger', weight: 1.14 },
        { holding: 'Visa', weight: 1.06 },
        { holding: 'Sirius XM', weight: 0.91 },
        { holding: 'Others', weight: 7.3 },
      ],
      categoryField: 'holding',
      valueField: 'weight',
      innerRadius: 0.48,
      outerRadius: 0.86,
      colors: [
        '#1E5AA8',
        '#E7C143',
        '#C7164F',
        '#D9222A',
        '#0EA86D',
        '#6E3CB6',
        '#F08A29',
        '#47B7E8',
        '#8C6B3E',
        '#3E7EEA',
        '#EF3F2A',
        '#0FA27A',
        '#4EAE50',
        '#D4A92C',
        '#9AA3AD',
      ],
      background: {
        color: '#F8F7F3',
      },
      label: {
        visible: true,
        position: 'spider',
        format: '{name} ({value}%)',
      },
      legend: { visible: false },
    },
  },
  {
    name: '清新主题 (fresh)',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（清新主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      theme: 'fresh',
    },
  },
  {
    name: '暖阳主题 (sunset)',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（暖阳主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      theme: 'sunset',
    },
  },
  {
    name: '浪漫主题 (romantic)',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（浪漫主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      theme: 'romantic',
    },
  },
  {
    name: '梦幻主题 (dream)',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（梦幻主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      theme: 'dream',
    },
  },
  {
    name: '霓虹主题 (neon)',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（霓虹主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      theme: 'neon',
    },
  },
  {
    name: '自定义主题',
    schema: {
      chartType: 'pie',
      title: { text: '产品销售分布（自定义主题）' },
      data: [
        { product: '手机', sales: 1200 },
        { product: '电脑', sales: 800 },
        { product: '平板', sales: 600 },
        { product: '手表', sales: 400 },
        { product: '耳机', sales: 300 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      customizedTheme: {
        type: 'light',
        colors: ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7'],
        backgroundColor: '#FFF5F5',
        textColor: '#222222',
        secondaryTextColor: '#666666',
      },
    },
  },
  {
    name: 'test',
    schema: {
      chartType: 'pie',
      title: {
        text: '2025 年全球原油及其他液体燃料产量占比（按地区）',
        position: 'center',
      },
      width: 800,
      height: 600,
      data: [
        {
          region: 'North America',
          productionMbpd: 31.8,
          sharePercent: 29.9,
        },
        {
          region: 'Middle East',
          productionMbpd: 31,
          sharePercent: 29.1,
        },
        {
          region: 'Eurasia (Russia, Kazakhstan, Azerbaijan)',
          productionMbpd: 13.6,
          sharePercent: 12.8,
        },
        {
          region: 'Asia-Pacific',
          productionMbpd: 9.4,
          sharePercent: 8.9,
        },
        {
          region: 'Central & South America',
          productionMbpd: 8.9,
          sharePercent: 8.4,
        },
        {
          region: 'Africa',
          productionMbpd: 7.6,
          sharePercent: 7.2,
        },
        {
          region: 'Europe',
          productionMbpd: 4,
          sharePercent: 3.7,
        },
      ],
      categoryField: 'region',
      valueField: 'sharePercent',
      innerRadius: 0.55,
      outerRadius: 0.85,
      background: {
        image:
          'https://images.pexels.com/photos/3855962/pexels-photo-3855962.jpeg?w=1920&h=1080&fit=crop',
      },
      theme: 'energy',
      legend: {
        visible: true,
        position: 'top',
      },
      label: {
        visible: true,
        position: 'spider',
        format: '{name} {percent}',
        minVisible: 2,
      },
      icon: {
        visible: true,
        field: 'region',
        size: 24,
        position: 'inside-inner',
        map: {
          'North America': 'https://api.iconify.design/mdi/oil.svg?color=%23ffffff',
          'Central & South America': 'https://api.iconify.design/mdi/oil-lamp.svg?color=%23ffffff',
          Europe: 'https://api.iconify.design/mdi/oil-level.svg?color=%23ffffff',
          'Eurasia (Russia, Kazakhstan, Azerbaijan)':
            'https://api.iconify.design/mdi/oil-truck.svg?color=%23ffffff',
          'Middle East': 'https://api.iconify.design/mdi/oil-saver.svg?color=%23ffffff',
          Africa: 'https://api.iconify.design/mdi/oil-barrel.svg?color=%23ffffff',
          'Asia-Pacific': 'https://api.iconify.design/mdi/oil-barrel-outline.svg?color=%23ffffff',
        },
      },
      centerImage: {
        visible: true,
        url: 'https://images.unsplash.com/vector-1769600501923-924c765e35fd?w=300&h=300&fit=crop',
        width: 80,
        height: 80,
      },
      footnote: {
        text: '总量：106.3 mb/d（mb/d=百万桶/日）；数据为 2025 年年平均值，占比为全球百分比。',
        layout: 'left',
      },
    },
  },
];
