import type { TreemapChartSchema } from '@visactor/vinfo-graphics';

export const treemapExamples: { name: string; schema: TreemapChartSchema }[] = [
  {
    name: '基础矩阵树图',
    schema: {
      chartType: 'treemap',
      title: { text: '部门预算分布' },
      data: [
        { dept: '技术部', budget: 250 },
        { dept: '市场部', budget: 180 },
        { dept: '运营部', budget: 150 },
        { dept: '人力部', budget: 80 },
        { dept: '财务部', budget: 60 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      theme: 'airline',
    },
  },
  {
    name: '带百分比标签',
    schema: {
      chartType: 'treemap',
      title: { text: '部门预算分布（百分比）' },
      data: [
        { dept: '技术部', budget: 250 },
        { dept: '市场部', budget: 180 },
        { dept: '运营部', budget: 150 },
        { dept: '人力部', budget: 80 },
        { dept: '财务部', budget: 60 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      label: {
        visible: true,
        showPercent: true,
        format: '{name}\n{percent}',
      },
    },
  },
  {
    name: '带排名标签',
    schema: {
      chartType: 'treemap',
      title: { text: '部门预算分布（带排名）' },
      data: [
        { dept: '技术部', budget: 250 },
        { dept: '市场部', budget: 180 },
        { dept: '运营部', budget: 150 },
        { dept: '人力部', budget: 80 },
        { dept: '财务部', budget: 60 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      rank: {
        visible: true,
        position: 'top-left',
        style: {
          fontSize: 12,
          fill: '#fff',
          fontWeight: 'bold',
          backgroundColor: 'rgba(0,0,0,0.5)',
        },
      },
    },
  },
  {
    name: '带间距和圆角',
    schema: {
      chartType: 'treemap',
      title: { text: '部门预算分布（带间距）' },
      data: [
        { dept: '技术部', budget: 250 },
        { dept: '市场部', budget: 180 },
        { dept: '运营部', budget: 150 },
        { dept: '人力部', budget: 80 },
        { dept: '财务部', budget: 60 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      node: {
        gap: 4,
        padding: 8,
        cornerRadius: 8,
      },
    },
  },
  {
    name: '自定义颜色',
    schema: {
      chartType: 'treemap',
      title: { text: '部门预算分布（自定义颜色）' },
      data: [
        { dept: '技术部', budget: 250 },
        { dept: '市场部', budget: 180 },
        { dept: '运营部', budget: 150 },
        { dept: '人力部', budget: 80 },
        { dept: '财务部', budget: 60 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      colors: ['#5B8FF9', '#5AD8A6', '#F6BD16', '#E86452', '#6DC8EC'],
    },
  },
  {
    name: '带图标',
    schema: {
      chartType: 'treemap',
      title: { text: '社交媒体市场份额' },
      data: [
        { platform: '微信', users: 1200, icon: 'wechat' },
        { platform: '抖音', users: 800, icon: 'douyin' },
        { platform: '微博', users: 600, icon: 'weibo' },
        { platform: '小红书', users: 400, icon: 'xiaohongshu' },
        { platform: '其他', users: 200, icon: 'other' },
      ],
      categoryField: 'platform',
      valueField: 'users',
      icon: {
        visible: true,
        field: 'icon',
        position: 'top-left',
        size: 28,
        offset: 10,
        map: {
          wechat: 'https://api.iconify.design/simple-icons/wechat.svg?color=%2307C160',
          douyin: 'https://api.iconify.design/simple-icons/tiktok.svg?color=%23000000',
          weibo: 'https://api.iconify.design/simple-icons/sinaweibo.svg?color=%23E6162D',
          xiaohongshu: 'https://api.iconify.design/simple-icons/xiaohongshu.svg?color=%23FF2442',
          other:
            'https://api.iconify.design/material-symbols/add-circle-outline-rounded.svg?color=%23666',
        },
      },
    },
  },
  {
    name: '分组模式',
    schema: {
      chartType: 'treemap',
      title: { text: '公司预算分布（按公司分组）' },
      data: [
        { dept: '前端组', company: 'A公司', budget: 100 },
        { dept: '后端组', company: 'A公司', budget: 150 },
        { dept: '测试组', company: 'A公司', budget: 80 },
        { dept: '前端组', company: 'B公司', budget: 90 },
        { dept: '后端组', company: 'B公司', budget: 120 },
        { dept: '设计组', company: 'B公司', budget: 60 },
        { dept: '前端组', company: 'C公司', budget: 70 },
        { dept: '后端组', company: 'C公司', budget: 100 },
      ],
      categoryField: 'dept',
      valueField: 'budget',
      groupField: 'company',
      node: {
        gap: 2,
        cornerRadius: 4,
      },
    },
  },
  {
    name: '分组模式带颜色',
    schema: {
      chartType: 'treemap',
      title: { text: '季度销售分布（按季度分组）' },
      data: [
        { product: '产品A', quarter: 'Q1', sales: 100 },
        { product: '产品B', quarter: 'Q1', sales: 80 },
        { product: '产品C', quarter: 'Q1', sales: 60 },
        { product: '产品A', quarter: 'Q2', sales: 120 },
        { product: '产品B', quarter: 'Q2', sales: 90 },
        { product: '产品C', quarter: 'Q2', sales: 70 },
        { product: '产品A', quarter: 'Q3', sales: 140 },
        { product: '产品B', quarter: 'Q3', sales: 100 },
        { product: '产品C', quarter: 'Q3', sales: 80 },
      ],
      categoryField: 'product',
      valueField: 'sales',
      groupField: 'quarter',
      colors: [
        '#5B8FF9',
        '#5AD8A6',
        '#F6BD16',
        '#E86452',
        '#6DC8EC',
        '#945FB9',
        '#FF9D6D',
        '#FFCC45',
        '#47B7E8',
      ],
      node: {
        gap: 3,
        cornerRadius: 6,
      },
    },
  },
  {
    name: '综合示例',
    schema: {
      chartType: 'treemap',
      title: { text: '手机品牌市场份额' },
      data: [
        { brand: 'Apple', share: 25, icon: 'apple' },
        { brand: 'Samsung', share: 22, icon: 'samsung' },
        { brand: 'Xiaomi', share: 18, icon: 'xiaomi' },
        { brand: 'OPPO', share: 12, icon: 'oppo' },
        { brand: 'vivo', share: 10, icon: 'vivo' },
        { brand: '其他', share: 13, icon: 'other' },
      ],
      categoryField: 'brand',
      valueField: 'share',
      node: {
        gap: 3,
        cornerRadius: 8,
      },
      label: {
        visible: true,
        showPercent: true,
      },
      rank: {
        visible: true,
        position: 'top-left',
        style: {
          fontSize: 14,
          fill: '#fff',
          fontWeight: 'bold',
          backgroundColor: 'rgba(0,0,0,0.6)',
        },
      },
      icon: {
        visible: true,
        field: 'icon',
        position: 'bottom-right',
        size: 40,
        offset: 0,
        map: {
          apple: 'https://api.iconify.design/simple-icons/apple.svg?color=%23000000',
          samsung: 'https://api.iconify.design/simple-icons/samsung.svg?color=%23000000',
          xiaomi: 'https://api.iconify.design/simple-icons/xiaomi.svg?color=%23000000',
          oppo: 'https://api.iconify.design/simple-icons/oppo.svg?color=%23000000',
          vivo: 'https://api.iconify.design/simple-icons/vivo.svg?color=%23000000',
          other: 'https://api.iconify.design/material-symbols/add-circle.svg?color=%23000000',
        },
      },
      colors: ['#333333', '#1428A0', '#FF6900', '#1AAD19', '#415FFF', '#9AA3AD'],
    },
  },

  {
    name: '图片背景节点',
    schema: {
      chartType: 'treemap',
      title: { text: '旅行主题热度（图片背景）' },
      data: [
        { place: '海边', score: 35, icon: 'beach', bg: 'beach' },
        { place: '雪山', score: 25, icon: 'mountain', bg: 'mountain' },
        { place: '森林', score: 20, icon: 'forest', bg: 'forest' },
        { place: '城市', score: 12, icon: 'city', bg: 'city' },
        { place: '沙漠', score: 8, icon: 'desert', bg: 'desert' },
      ],
      categoryField: 'place',
      valueField: 'score',
      node: {
        gap: 4,
        padding: 8,
        cornerRadius: 8,
      },
      label: {
        visible: true,
        showPercent: true,
      },
      icon: {
        visible: true,
        field: 'icon',
        position: 'top-left',
        size: 20,
        offset: 8,
        map: {
          beach: 'https://api.iconify.design/material-symbols/beach-access.svg?color=%23ffffff',
          mountain: 'https://api.iconify.design/material-symbols/landscape.svg?color=%23ffffff',
          forest: 'https://api.iconify.design/material-symbols/forest.svg?color=%23ffffff',
          city: 'https://api.iconify.design/material-symbols/location-city.svg?color=%23ffffff',
          desert: 'https://api.iconify.design/material-symbols/wb-sunny.svg?color=%23ffffff',
        },
      },
      nodeBackground: {
        field: 'bg',
        opacity: 0.28,
        map: {
          beach: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
          mountain: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
          forest: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
          city: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800',
          desert: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
        },
      },
      colors: ['#1f3b5c', '#2f4f6f', '#3d6b57', '#545e75', '#7a6a4f'],
    },
  },
  {
    name: '分组treemap+icon',
    schema: {
      chartType: 'treemap',
      title: {
        text: '全球最大公司市值 Treemap（单位：十亿美元）',
        position: 'center',
      },
      footnote: {
        text: '数据整理时间：2026-03-16；单位统一为十亿美元（B）',
        layout: 'left',
      },
      width: 1000,
      height: 700,
      background: {
        color: '#101322',
      },
      theme: 'dark',
      data: [
        {
          Rank: 1,
          Name: 'NVIDIA',
          'Market Cap': '$4.8T',
          Country: 'United States',
          MarketCapB: 4800,
        },
        {
          Rank: 2,
          Name: 'Apple',
          'Market Cap': '$4.0T',
          Country: 'United States',
          MarketCapB: 4000,
        },
        {
          Rank: 3,
          Name: 'Alphabet (Google)',
          'Market Cap': '$3.8T',
          Country: 'United States',
          MarketCapB: 3800,
        },
        {
          Rank: 4,
          Name: 'Microsoft',
          'Market Cap': '$3.0T',
          Country: 'United States',
          MarketCapB: 3000,
        },
        {
          Rank: 5,
          Name: 'Amazon',
          'Market Cap': '$2.3T',
          Country: 'United States',
          MarketCapB: 2300,
        },
        {
          Rank: 6,
          Name: 'TSMC',
          'Market Cap': '$2.0T',
          Country: 'Taiwan',
          MarketCapB: 2000,
        },
        {
          Rank: 7,
          Name: 'Saudi Aramco',
          'Market Cap': '$1.7T',
          Country: 'Saudi Arabia',
          MarketCapB: 1700,
        },
        {
          Rank: 8,
          Name: 'Meta Platforms (Facebook)',
          'Market Cap': '$1.7T',
          Country: 'United States',
          MarketCapB: 1700,
        },
        {
          Rank: 9,
          Name: 'Broadcom',
          'Market Cap': '$1.6T',
          Country: 'United States',
          MarketCapB: 1600,
        },
        {
          Rank: 10,
          Name: 'Tesla',
          'Market Cap': '$1.6T',
          Country: 'United States',
          MarketCapB: 1600,
        },
        {
          Rank: 11,
          Name: 'Berkshire Hathaway',
          'Market Cap': '$1.1T',
          Country: 'United States',
          MarketCapB: 1100,
        },
        {
          Rank: 12,
          Name: 'Walmart',
          'Market Cap': '$1.0T',
          Country: 'United States',
          MarketCapB: 1000,
        },
        {
          Rank: 13,
          Name: 'Eli Lilly',
          'Market Cap': '$972B',
          Country: 'United States',
          MarketCapB: 972,
        },
        {
          Rank: 14,
          Name: 'Samsung',
          'Market Cap': '$953B',
          Country: 'South Korea',
          MarketCapB: 953,
        },
        {
          Rank: 15,
          Name: 'JPMorgan Chase',
          'Market Cap': '$819B',
          Country: 'United States',
          MarketCapB: 819,
        },
        {
          Rank: 16,
          Name: 'Exxon Mobil',
          'Market Cap': '$629B',
          Country: 'United States',
          MarketCapB: 629,
        },
        {
          Rank: 17,
          Name: 'Visa',
          'Market Cap': '$604B',
          Country: 'United States',
          MarketCapB: 604,
        },
        {
          Rank: 18,
          Name: 'Tencent',
          'Market Cap': '$603B',
          Country: 'China',
          MarketCapB: 603,
        },
        {
          Rank: 19,
          Name: 'ASML',
          'Market Cap': '$593B',
          Country: 'Netherlands',
          MarketCapB: 593,
        },
        {
          Rank: 20,
          Name: 'Johnson & Johnson',
          'Market Cap': '$591B',
          Country: 'United States',
          MarketCapB: 591,
        },
        {
          Rank: 21,
          Name: 'SK Hynix',
          'Market Cap': '$493B',
          Country: 'South Korea',
          MarketCapB: 493,
        },
        {
          Rank: 22,
          Name: 'Micron Technology',
          'Market Cap': '$483B',
          Country: 'United States',
          MarketCapB: 483,
        },
        {
          Rank: 23,
          Name: 'Mastercard',
          'Market Cap': '$455B',
          Country: 'United States',
          MarketCapB: 455,
        },
        {
          Rank: 24,
          Name: 'Costco',
          'Market Cap': '$442B',
          Country: 'United States',
          MarketCapB: 442,
        },
        {
          Rank: 25,
          Name: 'Oracle',
          'Market Cap': '$425B',
          Country: 'United States',
          MarketCapB: 425,
        },
        {
          Rank: 26,
          Name: 'AbbVie',
          'Market Cap': '$401B',
          Country: 'United States',
          MarketCapB: 401,
        },
        {
          Rank: 27,
          Name: 'Procter & Gamble',
          'Market Cap': '$382B',
          Country: 'United States',
          MarketCapB: 382,
        },
        {
          Rank: 28,
          Name: 'Roche',
          'Market Cap': '$380B',
          Country: 'Switzerland',
          MarketCapB: 380,
        },
        {
          Rank: 29,
          Name: 'Bank of America',
          'Market Cap': '$378B',
          Country: 'United States',
          MarketCapB: 378,
        },
        {
          Rank: 30,
          Name: 'Home Depot',
          'Market Cap': '$374B',
          Country: 'United States',
          MarketCapB: 374,
        },
        {
          Rank: 31,
          Name: 'ICBC',
          'Market Cap': '$369B',
          Country: 'China',
          MarketCapB: 369,
        },
        {
          Rank: 32,
          Name: 'Chevron',
          'Market Cap': '$369B',
          Country: 'United States',
          MarketCapB: 369,
        },
        {
          Rank: 33,
          Name: 'Alibaba',
          'Market Cap': '$364B',
          Country: 'China',
          MarketCapB: 364,
        },
        {
          Rank: 34,
          Name: 'General Electric',
          'Market Cap': '$362B',
          Country: 'United States',
          MarketCapB: 362,
        },
        {
          Rank: 35,
          Name: 'Caterpillar',
          'Market Cap': '$359B',
          Country: 'United States',
          MarketCapB: 359,
        },
        {
          Rank: 36,
          Name: 'Netflix',
          'Market Cap': '$351B',
          Country: 'United States',
          MarketCapB: 351,
        },
        {
          Rank: 37,
          Name: 'Coca-Cola',
          'Market Cap': '$346B',
          Country: 'United States',
          MarketCapB: 346,
        },
        {
          Rank: 38,
          Name: 'AMD',
          'Market Cap': '$344B',
          Country: 'United States',
          MarketCapB: 344,
        },
        {
          Rank: 39,
          Name: 'Agricultural Bank of China',
          'Market Cap': '$332B',
          Country: 'China',
          MarketCapB: 332,
        },
        {
          Rank: 40,
          Name: 'China Construction Bank',
          'Market Cap': '$329B',
          Country: 'China',
          MarketCapB: 329,
        },
        {
          Rank: 41,
          Name: 'LVMH',
          'Market Cap': '$324B',
          Country: 'France',
          MarketCapB: 324,
        },
        {
          Rank: 42,
          Name: 'HSBC',
          'Market Cap': '$323B',
          Country: 'United Kingdom',
          MarketCapB: 323,
        },
        {
          Rank: 43,
          Name: 'Novartis',
          'Market Cap': '$323B',
          Country: 'Switzerland',
          MarketCapB: 323,
        },
        {
          Rank: 44,
          Name: 'Palantir',
          'Market Cap': '$321B',
          Country: 'United States',
          MarketCapB: 321,
        },
        {
          Rank: 45,
          Name: 'AstraZeneca',
          'Market Cap': '$320B',
          Country: 'United Kingdom',
          MarketCapB: 320,
        },
        {
          Rank: 46,
          Name: 'Toyota',
          'Market Cap': '$315B',
          Country: 'Japan',
          MarketCapB: 315,
        },
        {
          Rank: 47,
          Name: 'Applied Materials',
          'Market Cap': '$313B',
          Country: 'United States',
          MarketCapB: 313,
        },
        {
          Rank: 48,
          Name: 'Lam Research',
          'Market Cap': '$313B',
          Country: 'United States',
          MarketCapB: 313,
        },
        {
          Rank: 49,
          Name: 'Cisco',
          'Market Cap': '$313B',
          Country: 'United States',
          MarketCapB: 313,
        },
        {
          Rank: 50,
          Name: 'Merck',
          'Market Cap': '$306B',
          Country: 'United States',
          MarketCapB: 306,
        },
      ],
      categoryField: 'Name',
      valueField: 'MarketCapB',
      groupField: 'Country',
      legend: {
        visible: true,
        position: 'right',
      },
      node: {
        gap: 2,
        padding: 4,
        cornerRadius: 4,
      },
      label: {
        visible: true,
        format: '{name}\n{value}B',
        showPercent: false,
        minVisible: 30,
      },
      rank: {
        visible: true,
        position: 'top-left',
        style: {
          fontSize: 11,
          fill: '#ffffff',
          fontWeight: 600,
          backgroundColor: 'rgba(0,0,0,0.35)',
        },
      },
      icon: {
        visible: true,
        field: 'Country',
        map: {
          'Saudi Arabia': 'https://api.iconify.design/twemoji/flag-saudi-arabia.svg',
          China: 'https://api.iconify.design/twemoji/flag-china.svg',
          'United Kingdom': 'https://api.iconify.design/twemoji/flag-united-kingdom.svg',
          Japan: 'https://api.iconify.design/twemoji/flag-japan.svg',
          Taiwan: 'https://api.iconify.design/twemoji/flag-taiwan.svg',
          'South Korea': 'https://api.iconify.design/twemoji/flag-south-korea.svg',
          Netherlands: 'https://api.iconify.design/twemoji/flag-netherlands.svg',
        },
        size: 20,
        position: 'top-right',
      },
    },
  },
  {
    name: '分组treemap+icon+背景图',
    schema: {
      chartType: 'treemap',
      title: {
        text: '各国跨境外汇总额（矩阵树图）',
        position: 'center',
        subtext: '单位：$ 十亿美元（billions）｜数据来源：用户提供',
      },
      width: 1600,
      height: 900,
      data: [
        {
          name: '英国',
          value: 957,
          iconKey: 'United Kingdom',
        },
        {
          name: '美国',
          value: 653,
          iconKey: 'United States',
        },
        {
          name: '新加坡',
          value: 336,
          iconKey: 'Singapore',
        },
        {
          name: '其他地区',
          value: 154,
          iconKey: 'Other',
        },
        {
          name: '中国香港',
          value: 149,
          iconKey: 'Hong Kong',
        },
        {
          name: '瑞士',
          value: 85,
          iconKey: 'Switzerland',
        },
        {
          name: '德国',
          value: 74,
          iconKey: 'Germany',
        },
        {
          name: '日本',
          value: 71,
          iconKey: 'Japan',
        },
        {
          name: '澳洲',
          value: 40,
          iconKey: 'Australia',
        },
        {
          name: '法国',
          value: 27,
          iconKey: 'France',
        },
        {
          name: '加拿大',
          value: 24,
          iconKey: 'Canada',
        },
      ],
      categoryField: 'name',
      valueField: 'value',
      background: {
        color: '#FFFFFF',
      },
      colors: [
        '#0B4F6C',
        '#145DA0',
        '#007C92',
        '#1F7A8C',
        '#2391A8',
        '#27AABF',
        '#2FC2CF',
        '#39D8D6',
        '#65DADB',
        '#8DE0DF',
        '#B5E6E4',
      ],
      legend: {
        visible: false,
        position: 'bottom',
      },
      node: {
        gap: 2,
        padding: 6,
        cornerRadius: 4,
      },
      rank: {
        visible: true,
        position: 'top-left',
        style: {
          fontSize: 18,
          fill: '#FFFFFF',
          fontWeight: 700,
        },
      },
      icon: {
        field: 'iconKey',
        map: {
          'United Kingdom': 'https://api.iconify.design/twemoji/flag-united-kingdom.svg',
          'United States': 'https://api.iconify.design/twemoji/flag-united-states.svg',
          Singapore: 'https://api.iconify.design/twemoji/flag-singapore.svg',
          'Hong Kong': 'https://api.iconify.design/twemoji/flag-hong-kong-sar-china.svg',
          Switzerland: 'https://api.iconify.design/twemoji/flag-switzerland.svg',
          Germany: 'https://api.iconify.design/twemoji/flag-germany.svg',
          Japan: 'https://api.iconify.design/twemoji/flag-japan.svg',
          Australia: 'https://api.iconify.design/twemoji/flag-australia.svg',
          France: 'https://api.iconify.design/twemoji/flag-france.svg',
          Canada: 'https://api.iconify.design/twemoji/flag-canada.svg',
          Other: 'https://api.iconify.design/twemoji/world-map.svg',
        },
        visible: true,
        position: 'top-right',
        size: 26,
        offset: 4,
        style: {
          lineWidth: 1,
          stroke: 'rgba(255,255,255,0.9)',
        },
      },
      label: {
        visible: true,
        format: '{name}\n{value}',
        showPercent: true,
        minVisible: 90,
      },
      footnote: {
        text: '单位：$ 十亿美元（billions）｜数据来源：用户提供',
        layout: 'left',
        fontSize: 12,
        fill: '#64748B',
      },
    },
  },
];
